repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      exclude: ^public/|^themes/
    - id: end-of-file-fixer
      exclude: ^public/|^themes/
    - id: check-yaml
      exclude: ^public/|^themes/
    - id: check-toml
      exclude: ^public/|^themes/
    - id: check-added-large-files
    - id: detect-private-key
      exclude: ^public/|^themes/

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.1
  hooks:
    - id: gitleaks
      exclude: ^public/|^themes/
