baseURL = 'https://blog.tineochristopher.com/'
languageCode = 'en-us'
title = 'Christopher Tineo'
theme = 'PaperMod'

[params]
    env = 'production'
    title = 'Christopher Tineo'
    description = 'Software Engineer'
    author = 'Christopher Tineo'
    
    # Profile Mode (Home Page)
    [params.profileMode]
        enabled = true
        title = 'Christopher Tineo'
        subtitle = 'Building things and sharing thoughts.'
        imageUrl = 'https://media.licdn.com/dms/image/v2/D4E03AQGAwKLESo8Lrg/profile-displayphoto-scale_200_200/B4EZmpQCtaKoAY-/0/1759481181365?e=1772668800&v=beta&t=qm2Xde3s126Ru_DsrxecrPbbgxVIEeHKgW_o5E9e1u0'
        imageTitle = 'Christopher Tineo'
        imageWidth = 120
        imageHeight = 120
        
        [[params.profileMode.buttons]]
            name = 'Blog Posts'
            url = 'posts'
        
        [[params.profileMode.buttons]]
            name = 'Coffee Chat â˜•'
            url = 'https://calendar.app.google/2fADVvsqhLMpdNGa7'

    [[params.socialIcons]]
        name = 'linkedin'
        url = 'https://www.linkedin.com/in/christopher-tineo/'

[menu]
    [[menu.main]]
        identifier = 'about'
        name = 'About'
        url = '/about/'
        weight = 5
    [[menu.main]]
        identifier = 'posts'
        name = 'Posts'
        url = '/posts/'
        weight = 10
    [[menu.main]]
        identifier = 'coffee-chat'
        name = 'Coffee Chat'
        url = 'https://calendar.app.google/2fADVvsqhLMpdNGa7'
        weight = 20
    [[menu.main]]
        identifier = 'admin'
        name = 'Admin'
        url = '/admin/'
        weight = 30
