backend:
  name: github
  repo: TineoC/blog
  branch: main
  base_url: https://decap-oauth-gateway.tineochristopher.workers.dev

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    view_groups:
      - {label: "Draft Status", field: "draft"}
    view_filters:
      - {label: "Drafts", field: "draft", pattern: true}
      - {label: "Published", field: "draft", pattern: false}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
